### ISSUE TITLE
AttributeError: 'module' object has no attribute 'auto_update'

### ISSUE THREAD

**Issue by Kyle-Falconer** [DataShades/ckanext-cloudconnector#3]
I'm getting the following crash when trying to load the plugin: 

```
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/paster", line 11, in <module>
ckan          |     sys.exit(run())
ckan          |   File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 102, in run
ckan          |     invoke(command, command_name, options, args[1:])
ckan          |   File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 141, in invoke
ckan          |     exit_code = runner.run(args)
ckan          |   File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 236, in run
ckan          |     result = self.command()
ckan          |   File "/usr/local/lib/python2.7/dist-packages/paste/script/serve.py", line 284, in command
ckan          |     relative_to=base, global_conf=vars)
ckan          |   File "/usr/local/lib/python2.7/dist-packages/paste/script/serve.py", line 329, in loadapp
ckan          |     **kw)
ckan          |   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
ckan          |     return loadobj(APP, uri, name=name, **kw)
ckan          |   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
ckan          |     return context.create()
ckan          |   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
ckan          |     return self.object_type.invoke(self)
ckan          |   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
ckan          |     return fix_call(context.object, context.global_conf, **context.local_conf)
ckan          |   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
ckan          |     val = callable(*args, **kw)
ckan          |   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 45, in make_app
ckan          |     load_environment(conf, app_conf)
ckan          |   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 97, in load_environment
ckan          |     p.load_all()
ckan          |   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
ckan          |     load(*plugins)
ckan          |   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 153, in load
ckan          |     service = _get_service(plugin)
ckan          |   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 255, in _get_service
ckan          |     return plugin.load()(name=plugin_name)
ckan          |   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
ckan          |     return self.resolve()
ckan          |   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
ckan          |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ckan          |   File "/usr/local/lib/python2.7/dist-packages/ckanext_cloudconnector-0.1-py2.7.egg/ckanext/cloud_connector/plugin.py", line 6, in <module>
ckan          |     import ckanext.cloud_connector.action as action
ckan          |   File "/usr/local/lib/python2.7/dist-packages/ckanext_cloudconnector-0.1-py2.7.egg/ckanext/cloud_connector/action/__init__.py", line 1, in <module>
ckan          |     from create import *
ckan          |   File "/usr/local/lib/python2.7/dist-packages/ckanext_cloudconnector-0.1-py2.7.egg/ckanext/cloud_connector/action/create.py", line 4, in <module>
ckan          |     import ckanext.cloud_connector.s3.uploader as uploader
ckan          |   File "/usr/local/lib/python2.7/dist-packages/ckanext_cloudconnector-0.1-py2.7.egg/ckanext/cloud_connector/s3/uploader.py", line 23, in <module>
ckan          |     auto_update = app_globals.auto_update
ckan          | AttributeError: 'module' object has no attribute 'auto_update'
ckan exited with code 1
```

You can check out my setup and CKAN configuration file in [VTA's Open Data Portal repository](https://github.com/vta/Open-Data-Portal/tree/dace2df79deff5eff039bcb9eb09fe5045f42be9). Using this code will reproduce the issue (this repository is self-contained and will work with docker-compose, provided you follow the database setup instructions).

**Comment by MrkGrgsn** [comment]
Hi @Kyle-Falconer. This extension is not being actively supported.  I suggest having a look at https://github.com/open-data/ckanext-cloudstorage which uses apache libcloud to support several cloud storage providers.

**Comment by Kyle-Falconer** [comment]
@MrkGrgsn good to know! Thanks for pointing me to the other plugin.
